import { Kata } from './types';

export const SHOTOKAN_KATAS: Kata[] = [
  { id: 'heian-shodan', name: 'Heian Shodan', translation: 'Peaceful Mind, First Level' },
  { id: 'heian-nidan', name: 'Heian Nidan', translation: 'Peaceful Mind, Second Level' },
  { id: 'heian-sandan', name: 'Heian Sandan', translation: 'Peaceful Mind, Third Level' },
  { id: 'heian-yondan', name: 'Heian Yondan', translation: 'Peaceful Mind, Fourth Level' },
  { id: 'heian-godan', name: 'Heian Godan', translation: 'Peaceful Mind, Fifth Level' },
  { id: 'tekki-shodan', name: 'Tekki Shodan', translation: 'Iron Horse, First Level' },
  { id: 'tekki-nidan', name: 'Tekki Nidan', translation: 'Iron Horse, Second Level' },
  { id: 'tekki-sandan', name: 'Tekki Sandan', translation: 'Iron Horse, Third Level' },
  { id: 'bassai-dai', name: 'Bassai Dai', translation: 'To Penetrate a Fortress (Major)' },
  { id: 'bassai-sho', name: 'Bassai Sho', translation: 'To Penetrate a Fortress (Minor)' },
  { id: 'kanku-dai', name: 'Kanku Dai', translation: 'To View the Sky (Major)' },
  { id: 'kanku-sho', name: 'Kanku Sho', translation: 'To View the Sky (Minor)' },
  { id: 'jion', name: 'Jion', translation: 'Temple Sound' },
  { id: 'jitte', name: 'Jitte', translation: 'Ten Hands' },
  { id: 'jiin', name: 'Jiin', translation: 'Temple Grounds' },
  { id: 'empi', name: 'Empi', translation: 'Flying Swallow' },
  { id: 'hangetsu', name: 'Hangetsu', translation: 'Half Moon' },
  { id: 'gankaku', name: 'Gankaku', translation: 'Crane on a Rock' },
  { id: 'nijushiho', name: 'Nijushiho', translation: 'Twenty-Four Steps' },
  { id: 'sochin', name: 'Sochin', translation: 'Preserve Peace' },
  { id: 'unsu', name: 'Unsu', translation: 'Cloud Hands' },
  { id: 'wankan', name: 'Wankan', translation: 'King\'s Crown' },
  { id: 'meikyo', name: 'Meikyo', translation: 'Bright Mirror' },
  { id: 'gojushiho-dai', name: 'Gojushiho Dai', translation: 'Fifty-Four Steps (Major)' },
  { id: 'gojushiho-sho', name: 'Gojushiho Sho', translation: 'Fifty-Four Steps (Minor)' },
  { id: 'chinte', name: 'Chinte', translation: 'Unusual Hands' }
];